In [1]:
import numpy as np

# ======================= 1. VECTOR 1D ==========================
# Tạo vector ngẫu nhiên
v1 = np.random.randint(1, 10, size=5)  # vector 1 chiều gồm 5 phần tử
v2 = np.random.randint(1, 10, size=5)

print("Vector v1:", v1)
print("Vector v2:", v2)

# 1) Cộng vector
print("v1 + v2 =", v1 + v2)

# 2) Trừ vector
print("v1 - v2 =", v1 - v2)

# 3) Nhân từng phần tử
print("v1 * v2 =", v1 * v2)

# 4) Chia từng phần tử
print("v1 / v2 =", v1 / v2)

# ======================= 2. MA TRẬN 2D ==========================
# Tạo ma trận ngẫu nhiên 3x3
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

print("\nMa trận A:\n", A)
print("Ma trận B:\n", B)

# 5) Cộng ma trận
print("A + B =\n", A + B)

# 6) Trừ ma trận
print("A - B =\n", A - B)

# 7) Nhân ma trận (theo kiểu element-wise)
print("A * B =\n", A * B)

# 8) Nhân ma trận (theo đại số tuyến tính)
print("A @ B =\n", A @ B)

# ======================= 3. THAO TÁC MA TRẬN ==========================
# 9) Chuyển vị
print("A^T =\n", A.T)

# 10) Trích 1 dòng
print("Dòng 1 của A:", A[0])

# 11) Trích 1 cột
print("Cột 2 của A:", A[:, 1])

# 12) Tách ma trận (cắt theo cột)
A1, A2, A3 = np.hsplit(A, 3)  # tách thành 3 cột riêng
print("Tách A thành 3 cột:")
print("A1:\n", A1)
print("A2:\n", A2)
print("A3:\n", A3)


# 13) Tách ma trận (cắt theo dòng)
B1, B2, B3 = np.vsplit(B, 3)  # tách thành 3 dòng riêng
print("Tách B thành 3 dòng:")
print("B1:\n", B1)
print("B2:\n", B2)
print("B3:\n", B3)

# 14) Nối ma trận (theo cột)
C = np.hstack((A, B))
print("Nối ngang A và B:\n", C)

# 15) Nối ma trận (theo dòng)
D = np.vstack((A, B))
print("Nối dọc A và B:\n", D)



Vector v1: [5 6 1 4 4]
Vector v2: [3 7 3 4 5]
v1 + v2 = [ 8 13  4  8  9]
v1 - v2 = [ 2 -1 -2  0 -1]
v1 * v2 = [15 42  3 16 20]
v1 / v2 = [1.66666667 0.85714286 0.33333333 1.         0.8       ]

Ma trận A:
 [[6 8 6]
 [9 3 6]
 [5 3 7]]
Ma trận B:
 [[4 5 6]
 [3 9 7]
 [7 2 2]]
A + B =
 [[10 13 12]
 [12 12 13]
 [12  5  9]]
A - B =
 [[ 2  3  0]
 [ 6 -6 -1]
 [-2  1  5]]
A * B =
 [[24 40 36]
 [27 27 42]
 [35  6 14]]
A @ B =
 [[ 90 114 104]
 [ 87  84  87]
 [ 78  66  65]]
A^T =
 [[6 9 5]
 [8 3 3]
 [6 6 7]]
Dòng 1 của A: [6 8 6]
Cột 2 của A: [8 3 3]
Tách A thành 3 cột:
A1:
 [[6]
 [9]
 [5]]
A2:
 [[8]
 [3]
 [3]]
A3:
 [[6]
 [6]
 [7]]
Tách B thành 3 dòng:
B1:
 [[4 5 6]]
B2:
 [[3 9 7]]
B3:
 [[7 2 2]]
Nối ngang A và B:
 [[6 8 6 4 5 6]
 [9 3 6 3 9 7]
 [5 3 7 7 2 2]]
Nối dọc A và B:
 [[6 8 6]
 [9 3 6]
 [5 3 7]
 [4 5 6]
 [3 9 7]
 [7 2 2]]
